// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtvsQd4HFHh_kdbdQvyzfBLroE7pgxgK4',
    appId: '1:982401879467:web:267517f718015f71d056ee',
    messagingSenderId: '982401879467',
    projectId: 'ecommerceapp-31393',
    authDomain: 'ecommerceapp-31393.firebaseapp.com',
    storageBucket: 'ecommerceapp-31393.firebasestorage.app',
    measurementId: 'G-G2YDYH41LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOMHeDVwGXosILZmrffz6bHSTbqO_bBuA',
    appId: '1:982401879467:android:6b15acd43e06332cd056ee',
    messagingSenderId: '982401879467',
    projectId: 'ecommerceapp-31393',
    storageBucket: 'ecommerceapp-31393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeUVX8-cHINej4dgpRLeth0W33dqcCSZY',
    appId: '1:982401879467:ios:a9080ded989048f2d056ee',
    messagingSenderId: '982401879467',
    projectId: 'ecommerceapp-31393',
    storageBucket: 'ecommerceapp-31393.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtvsQd4HFHh_kdbdQvyzfBLroE7pgxgK4',
    appId: '1:982401879467:web:5a1aff4e9c751a1ed056ee',
    messagingSenderId: '982401879467',
    projectId: 'ecommerceapp-31393',
    authDomain: 'ecommerceapp-31393.firebaseapp.com',
    storageBucket: 'ecommerceapp-31393.firebasestorage.app',
    measurementId: 'G-CQG8MZWTR6',
  );
}
